### PR TITLE
runTest: handle "exit" event

### PR DESCRIPTION
**Pull request by tal-sapan**
See https://github.com/microsoft/vscode-test/issues/74

### CODE REVIEW

**Comment by tal-sapan** [comment]
Hi,

Is there any progress with the review of this PR?

Thanks,
Tal

**Review by bpasero — CHANGES_REQUESTED** [review]
The `close` and `exit` handler could really benefit from sharing the code as it seems like a copy.

**Comment by tal-sapan** [comment]
> The `close` and `exit` handler could really benefit from sharing the code as it seems like a copy.

I extracted the function.

**Review by bpasero — APPROVED** [review]

**Comment by bpasero** [comment]
Thanks 👍 . Let me try to publish this as `1.4.1`

**Pull request merged**
